# Generated by Django 3.1.1 on 2023-12-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20231223_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdeliveryinfo',
            old_name='session_id',
            new_name='liqpay_data',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='orderdeliveryinfo',
            name='liqpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderdeliveryinfo',
            name='recipient_depart_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
