# Generated by Django 3.1.1 on 2023-12-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20231225_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryinfo',
            name='total_weight',
            field=models.FloatField(null=True),
        ),
    ]
