# Generated by Django 3.1.1 on 2023-12-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_orderdeliveryinfo_total_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliveryinfo',
            name='liqpay_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
