# Generated by Django 3.1.1 on 2023-08-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
