# Generated by Django 3.1.1 on 2023-12-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='net_mass',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
