# Generated by Django 3.1.1 on 2023-12-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_net_mass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='net_mass',
        ),
        migrations.AddField(
            model_name='products',
            name='gross_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса Брутто'),
        ),
    ]
