# Generated by Django 3.1.1 on 2024-01-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_commentproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='application_method',
            field=models.TextField(blank=True, null=True, verbose_name='Спосіб застосування'),
        ),
        migrations.AddField(
            model_name='products',
            name='features',
            field=models.TextField(blank=True, null=True, verbose_name='Особливості'),
        ),
    ]
