# Generated by Django 3.1.1 on 2023-12-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231205_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='depth',
            field=models.FloatField(blank=True, null=True, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='products',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Висота'),
        ),
        migrations.AddField(
            model_name='products',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина'),
        ),
    ]
