# Generated by Django 3.1.1 on 2024-01-09 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240109_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='application_method',
        ),
        migrations.CreateModel(
            name='ApplicationMethodProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Спосіб застосування')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
