# Generated by Django 3.1.1 on 2024-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240110_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentproduct',
            name='is_like',
        ),
        migrations.AddField(
            model_name='commentproduct',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commentproduct',
            name='rating_product',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
