# Generated by Django 3.1.1 on 2024-01-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240116_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.subsubcategory'),
        ),
    ]
